3scale/3scale_toolbox

Gemfile
README.md
exe/3scale-copy
lib/3scale_toolbox/cli.rb

```shell
bundle exec exe/3scale copy --endpoint=http://michal-admin.3scale.net.dev:3000  --provider-key=p service  1006371740392
```

poc of copy service command

---

.travis.yml
3scale_toolbox.gemspec
CHANGELOG.md
exe/3scale-copy
lib/3scale_toolbox/version.rb

release 0.1.1
* copy mapping rules
* copy proxy
/cc @vdel26

Copy mapping rules

---

.travis.yml
CHANGELOG.md
exe/3scale-copy

[travis] test 3scale copy help

---

.gitignore
.travis.yml
README.md
docs/import.md
examples/import.csv
exe/3scale-import

closes https://github.com/3scale/3scale_toolbox/issues/7

Import from CSV file

---

exe/3scale-copy

closes https://github.com/3scale/3scale_toolbox/issues/8

Target system name option in the copy command

---

docs/import.md
exe/3scale-import

closes https://github.com/3scale/3scale_toolbox/issues/15

Cannot import mapping rules

---

README.md

So we can point people to more low level stuff.

Mention 3scale API Client in the readme.

---

CHANGELOG.md
lib/3scale_toolbox/version.rb

release 0.3.0

---

exe/3scale-update

Fixes https://github.com/3scale/3scale_toolbox/pull/28 according to comments

Overwrite service

---

CHANGELOG.md
README.md
docs/ssl_errors.md
lib/3scale_toolbox/commands/3scale_command.rb
lib/3scale_toolbox/commands/copy_command/copy_service.rb
lib/3scale_toolbox/commands/import_command/import_csv.rb
lib/3scale_toolbox/commands/update_command/update_service.rb
spec/unit/copy_service_spec.rb
spec/unit/import_csv_spec.rb
spec/unit/update_service_spec.rb

Enable insecure connections with flag for all commands
Requires https://github.com/3scale/3scale-api-ruby v0.1.6
Fixes #59

Insecure connections

---

docs/plugins.md

Improved some minor grammar points

Minor grammar improvements

---

docs/remotes.md

I made some small wording change suggestions.
We should come up with a new term for "instance" I think, as generally people think that an instance is a separate install.
Added "list" to the synopsis

Some wording changes and fix error in command list

---

3scale_toolbox.gemspec
README.md
docs/plugins.md
lib/3scale_toolbox/commands/3scale_command.rb
lib/3scale_toolbox/commands/copy_command.rb
lib/3scale_toolbox/commands/copy_command/copy_service.rb
lib/3scale_toolbox/commands/import_command.rb
lib/3scale_toolbox/commands/import_command/import_csv.rb
lib/3scale_toolbox/commands/remote_command.rb
lib/3scale_toolbox/commands/remote_command/remote_add.rb
lib/3scale_toolbox/commands/remote_command/remote_list.rb
lib/3scale_toolbox/commands/remote_command/remote_remove.rb
lib/3scale_toolbox/commands/remote_command/remote_rename.rb
lib/3scale_toolbox/commands/update_command.rb
lib/3scale_toolbox/commands/update_command/update_service.rb

Improve README.md doc and command doc

---

docs/openapi.md

Documentation update to be consistent with last implementation updates

docs/openapi: fix doc to update service by system_name

---

lib/3scale_toolbox/cli.rb

Register signal trap on signals supported by OS

windows does not support USR1 signal

---

lib/3scale_toolbox/commands/import_command/openapi/create_service_step.rb
lib/3scale_toolbox/commands/import_command/openapi/update_policies_step.rb
lib/3scale_toolbox/commands/import_command/openapi/update_service_oidc_conf_step.rb
lib/3scale_toolbox/commands/import_command/openapi/update_service_proxy_step.rb
lib/3scale_toolbox/entities/service.rb
lib/3scale_toolbox/swagger/swagger.rb
spec/integration/import_openapi_spec.rb
spec/resources/oidc.yaml
spec/unit/commands/import_command/openapi/update_policies_spec.rb
spec/unit/commands/import_command/openapi/update_service_oidc_conf_spec.rb
spec/unit/commands/import_command/openapi/update_service_proxy_spec.rb
spec/unit/entities/service_spec.rb
spec/unit/swagger/swagger_spec.rb

Swagger parser: whitelist for  path object elements

---

.travis.yml
3scale_toolbox.gemspec

ruby 2.3 is in EOL
Support ruby 2.6

deprecate ruby 2.3, welcome ruby 2.6

---

Dockerfile

Build docker image for master branch
@miguelsorianod any improvement on Dockerfile will be appreciated

Dockerfile: build toolbox image

---

lib/3scale_toolbox/tasks/copy_limits_task.rb
lib/3scale_toolbox/tasks/copy_pricingrules_task.rb
spec/integration/copy_service_spec.rb
spec/integration/update_all_service_spec.rb
spec/unit/tasks/copy_limits_task_spec.rb
spec/unit/tasks/copy_pricingrules_task_spec.rb

fix app_plan limits and pricingrules match rules

---

CHANGELOG.md
docs/openapi.md
lib/3scale_toolbox/commands/import_command/openapi.rb

Improves import openapi help command

---

README.md
docs/service.md
lib/3scale_toolbox/commands.rb
lib/3scale_toolbox/commands/copy_command/copy_service.rb
lib/3scale_toolbox/commands/import_command/openapi/create_service_step.rb
lib/3scale_toolbox/commands/service_command.rb
lib/3scale_toolbox/commands/service_command/apply_command.rb
lib/3scale_toolbox/commands/service_command/create_command.rb
lib/3scale_toolbox/commands/service_command/delete_command.rb
lib/3scale_toolbox/commands/service_command/list_command.rb
lib/3scale_toolbox/commands/service_command/show_command.rb
lib/3scale_toolbox/entities/service.rb
spec/helpers.rb
spec/integration/commands/service_command/apply_command_spec.rb
spec/integration/commands/service_command/create_command_spec.rb
spec/integration/commands/service_command/delete_command_spec.rb
spec/integration/commands/service_command/list_command_spec.rb
spec/integration/commands/service_command/show_command_spec.rb
spec/integration/plan_export_spec.rb
spec/integration/plan_import_spec.rb
spec/unit/commands/import_command/openapi/create_service_step_spec.rb
spec/unit/commands/service_command/apply_command_spec.rb
spec/unit/commands/service_command/create_command_spec.rb
spec/unit/commands/service_command/delete_command_spec.rb
spec/unit/commands/service_command/list_command_spec.rb
spec/unit/commands/service_command/show_command_spec.rb
spec/unit/entities/service_spec.rb

Adds the 'service' subcommand in the CLI.
This should cover issue https://github.com/3scale/3scale_toolbox/issues/40
* Pending to add tests

Add 'service' subcommand with associated operations

---

CHANGELOG.md
lib/3scale_toolbox/version.rb

release 0.11.0

---

lib/3scale_toolbox/commands/plans_command/apply_command.rb
spec/unit/commands/plans_command/apply_command_spec.rb

Second call to `3scale application-plan apply --hiden` command failed because application plan was already hidden

application plan apply: make idempotent for hidden and published THREESCALE-2803

---

lib/3scale_toolbox/commands/import_command/openapi/create_activedocs_step.rb
spec/unit/commands/import_command/openapi/create_activedocs_step_spec.rb

fix leaking the SSO Issuer Endpoint secrets in the ActiveDocs THREESCALE-2863

---

lib/3scale_toolbox/entities/application.rb
spec/unit/entities/application_spec.rb

application apply: make idempotent --resume and --suspend THREESCALE-2844

---

3scale_toolbox.gemspec
lib/3scale_toolbox/commands/application_command/apply_command.rb
lib/3scale_toolbox/entities/application.rb
spec/unit/commands/application_command/apply_command_spec.rb
spec/unit/entities/application_spec.rb

Fix: create new app if app_id exists in another service THREESCALE-2892

---

lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb
lib/3scale_toolbox/commands/import_command/openapi/method.rb
lib/3scale_toolbox/commands/import_command/openapi/threescale_api_spec.rb
lib/3scale_toolbox/swagger/swagger.rb
spec/unit/commands/import_command/openapi/create_methods_step_spec.rb

* import openapi: include method object description
* import openapi: create methods process idempotent

 import openapi: include method object description  THREESCALE-2612

---

docs/applications.md
lib/3scale_toolbox/entities/account.rb
spec/unit/entities/account_spec.rb

Search the account by several fields THREESCALE-2867

---

.gitignore
Gemfile.lock

tracking Gemfile.lock

---

.circleci/config.yml
spec/integration/commands/applications_command/apply_command_spec.rb
spec/integration/commands/applications_command/create_command_spec.rb
spec/integration/commands/applications_command/delete_command_spec.rb
spec/integration/commands/applications_command/list_command_spec.rb
spec/integration/commands/applications_command/show_command_spec.rb
spec/integration/commands/methods_command/apply_command_spec.rb
spec/integration/commands/methods_command/create_command_spec.rb
spec/integration/commands/methods_command/delete_command_spec.rb
spec/integration/commands/methods_command/list_command_spec.rb
spec/integration/commands/metrics_command/apply_command_spec.rb
spec/integration/commands/metrics_command/create_command_spec.rb
spec/integration/commands/metrics_command/delete_command_spec.rb
spec/integration/commands/metrics_command/list_command_spec.rb
spec/integration/commands/plans_command/apply_command_spec.rb
spec/integration/commands/plans_command/create_command_spec.rb
spec/integration/commands/plans_command/delete_command_spec.rb
spec/integration/commands/plans_command/list_command_spec.rb
spec/integration/commands/plans_command/show_command_spec.rb

* application plan apply command
* application plan create command
* application plan list command
* application plan delete command
* application plan show command
* method create command
* method apply command
* method list command
* method delete command
* metric apply command
* metric create command
* metric delete command
* metric list command
* application list command
* application create command
* application show command
* application apply command
* application delete command

ApplicationPlan, Method, Metric and Application integration test

---

lib/3scale_toolbox/commands/proxy_config_command/export_command.rb

Proxy config export: do not fail if some product does not have proxy config

Proxy config export: do not fail if some product does not have proxy config

---

README.md
docs/activedocs.md
docs/app-plan.md
docs/applications.md
docs/copy-backend.md
docs/copy-policy-registry.md
docs/copy-product.md
docs/copy-service.md

Suggesting a few typo/grammatical changes.

[Minor] Typo/Grammatical Changes

---

lib/3scale_toolbox/commands/plans_command/show_command.rb

https://issues.redhat.com/browse/THREESCALE-5542

remove end_user_requirement field from application_plan show command

---

lib/3scale_toolbox/commands/service_command/copy_command/copy_methods_task.rb
spec/unit/commands/service_command/copy_command/copy_methods_task_spec.rb

https://issues.redhat.com/browse/THREESCALE-6764

copy methods includes description

---

.circleci/config.yml
.circleci/setup-rubygems.sh

Push to rubygems automatically when test pass and on tags

automate push to rubygems

---

lib/3scale_toolbox/commands/import_command/openapi/create_activedocs_step.rb

https://issues.redhat.com/browse/THREESCALE-6884

Fix openapi import for self managed services when production url is not set

---

.travis.yml
.travis/build_ppc64le.sh
.travis/setup_ppc64le_env.sh

power builds in TravisCI

---

lib/3scale_toolbox/commands/import_command/import_csv.rb
lib/3scale_toolbox/entities/account.rb
lib/3scale_toolbox/proxy_logger.rb
lib/3scale_toolbox/remote_cache.rb

https://issues.redhat.com/browse/THREESCALE-7387

remove warning from ruby 2.7 when last arg is keyword

---

docs/openapi.md

Explained how 3scale is configured from the OpenAPI document. Which parts of the OpenAPI document are used, and how, to configure 3scale.
Also added documentation about the minimum OpenAPI Document requried to configure a working 3scale product.
https://issues.redhat.com/browse/THREESCALE-4712

enhance importing OpenAPI doc

---

docs/copy-product.md
lib/3scale_toolbox/commands/backend_command/copy_command.rb
lib/3scale_toolbox/commands/import_command/openapi/create_activedocs_step.rb
lib/3scale_toolbox/commands/product_command/copy_command.rb
spec/unit/commands/import_command/openapi/update_policies_spec.rb
spec/unit/commands/methods_command/apply_command_spec.rb
spec/unit/commands/metrics_command/apply_command_spec.rb

https://issues.redhat.com/browse/THREESCALE-7215

Fix product copy command description

---

lib/3scale_toolbox/commands/import_command/openapi/update_policies_step.rb
spec/unit/commands/import_command/openapi/update_policies_spec.rb

When a product already contains an anonymous policy configured, if `3scale import openapi` is used with security requriements, the anonymous policy is not removed (and should be).
This PR fixes that. It is easy to test. Import OAS without sec requirements, then add security reqs to the same OAS and import to 3scale. The product should not have the anonymous policy configured in the first step.

import oas: reconciliate anonymous policy

---

lib/3scale_toolbox/commands/service_command/show_command.rb
lib/3scale_toolbox/entities/service.rb

https://issues.redhat.com/browse/THREESCALE-7916

remove end_user_registration_required field from service commands

---

.circleci/config.yml

docker image floating tags can be cached.
Remove existing cached images

fix docker container test

---

examples/petstore_simple.yaml
examples/petstore_simple_no_servers.yaml
lib/3scale_toolbox/commands/remote_command/remote_add.rb
lib/3scale_toolbox/helper.rb
lib/3scale_toolbox/openapi/oas3.rb
lib/3scale_toolbox/remotes.rb
spec/shared_oas3_contexts.rb
spec/unit/openapi/oas3_spec.rb

Fixes https://github.com/3scale/3scale_toolbox/issues/379

support for oas3 relative server url

---

CHANGELOG.md
Gemfile
Gemfile.lock
lib/3scale_toolbox/version.rb
licenses.xml

release v1.0.1
