- bin/setup
Project needs bundler version 1.11.* or newer (1.11.2 in fact)
> Make sure a compatible version of bundler is installed before we run bundle install

- README.md
Probably was renamed.
To run, use: "bundle exec 3scale"
> fix name of executable in readme.me

- .travis.yml
- 3scale_toolbox.gemspec
- CHANGELOG.md
closes #24
closes #29
this drops support for JRuby because of https://github.com/rubygems/rubygems/issues/1263
> [gemspec] require ruby >= 2.1

- exe/3scale-copy
I added "backend_version" to 3scale-copy.
We will be able to copy not only "API Key (user_key)" services but also "App_ID and App_Key Pair", "OAuth 2.0" and "OpenID Connect" services.
However, currently we cannot copy "OpenID Connect" services because of "https://issues.jboss.org/browse/THREESCALE-571".
> Support backend_version

- docs/plugins.md
I found out `cri` library supports *commands* to have state per execution.
Example has been documented.
> docs/plugins: command runner class example

- 3scale_toolbox.gemspec
[Ruby 2.3 by Software Collections](https://www.softwarecollections.org/en/scls/rhscl/rh-ruby23/) includes bundler which version (1.10) conflicts with required bundler version (1.11) right now. 
http://mirror.centos.org/centos/7/sclo/x86_64/rh/rh-ruby23/
Removing this requirement to enable RPM packaging for RHEL 7 with Ruby 2.3 enabled by Software Collections
> 3scale_toolbox.gemspec: remove bundler devel dep

- README.md
- lib/3scale_toolbox/commands/3scale_command.rb
- lib/3scale_toolbox/commands/copy_command.rb
- lib/3scale_toolbox/commands/copy_command/copy_service.rb
- lib/3scale_toolbox/commands/import_command.rb
- lib/3scale_toolbox/commands/import_command/import_csv.rb
- lib/3scale_toolbox/commands/update_command.rb
- lib/3scale_toolbox/commands/update_command/update_service.rb
* New documentation for `update service` command
* Improve documentation for `copy` and `import` commands.
* Remove unnecessary help flag
* Add TOC to README
> Toolbox documentation

- lib/3scale_toolbox/commands.rb
- lib/3scale_toolbox/commands/copy_command/copy_service.rb
- lib/3scale_toolbox/commands/update_command/update_service.rb
- spec/shared_contexts.rb
- spec/unit/copy_service_spec.rb
- spec/unit/update_service_spec.rb
New required attributes of the service are available now, https://github.com/3scale/porta/issues/133.
Add them on copy/update service commands. 
Does not fix entirely https://github.com/3scale/3scale_toolbox/issues/32, but this is an improvement.
> include new available attributes on copy/update service

- lib/3scale_toolbox/commands/update_command/update_service.rb
- spec/shared_examples.rb
- spec/spec_helper.rb
- spec/unit/update_service_spec.rb
When updating service from source to destination, source `system_name` is being sent to update destination `system_name`. This is a problem when updating services within the same tenant, since you would get the  following error from API:
```json
{"system_name": ["has already been taken"]}
```
The fix is: do not try to overwrite system name, unless specified using command's new optional argument with option `-t, --target_system_name`
> update service: only include system_name when specified in options

- .dependency_decisions.yml
- .travis.yml
- Gemfile
- Rakefile
Two rake tasks added:
* License finder check `license_finder:check`
* License finder report  `license_finder:report`
License finder check added on CI
License whitelist and approval list on `/.dependency_decisions.yml`
Note: Only CSV format report
> License finder

- lib/3scale_toolbox/commands/import_command/openapi/method.rb
- spec/unit/commands/import_command/openapi/method_spec.rb
in OAS 2.0, when there is no `operation_id` attribute, i.e.
```json
....
"paths": {
"/products": {
"get": {
"summary": "Product Types",
"description": "The Products endpoint returns information about the Uber products offered at a given location. The response includes the display name and other details about each product, and lists the products in the proper display order.",
"parameters": [
{
"name": "latitude",
"in": "query",
"description": "Latitude component of location.",
"required": true,
"type": "number",
"format": "double"
},
{
"name": "longitude",
"in": "query",
"description": "Longitude component of location.",
"required": true,
"type": "number",
"format": "double"
}
],
"tags": [
"Products"
],
"responses": {
"200": {
"description": "An array of products",
"schema": {
"type": …
```
> import openapi: fix when missing operation id in spec

- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/create_activedocs_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/step.rb
- lib/3scale_toolbox/entities/service.rb
- spec/integration/import_openapi_spec.rb
- spec/resources/petstore.yaml
- spec/unit/commands/import_command/openapi/create_activedocs_step_spec.rb
- spec/unit/commands/import_command/openapi_spec.rb
The OpenAPI Specification used to create the service is pushed as an ActiveDocs file, using the same system_name as the service.
This PR partially covers issue #90 
Still missing: This OpenAPI Specification is patched to take into account the new environment:
* the host field is updated with the hostname component of the public production base URL
* the schemes field is updated with the scheme component of the public production base URL
* the basePath field is updated if rewriting rules have been set
* the securityDefinitions/*/authorizationUrl and securityDefinitions/*/tokenUrl fields are updated with the token and authorize endpoints listed in the OpenID Connect wellknown endpoint (when OIDC is in use)
The missing parts will be included in another PR
> Import oas include activedocs

- docs/openapi.md
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/create_activedocs_step.rb
- spec/integration/import_openapi_spec.rb
- spec/unit/commands/import_command/openapi/create_activedocs_step_spec.rb
When importing OAS, ActiveDoc is created by default on `visible` state
Fixes #108
> ActiveDocs created in published state

- 3scale_toolbox.gemspec
- lib/3scale_toolbox.rb
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/resource_reader.rb
- lib/3scale_toolbox/commands/import_command/openapi/threescale_api_spec.rb
- lib/3scale_toolbox/swagger.rb
- lib/3scale_toolbox/swagger/swagger.rb
- resources/swagger_meta_schema.json
- spec/unit/commands/import_command/openapi/resource_reader_spec.rb
- spec/unit/commands/import_command/openapi/threescale_api_spec_spec.rb
- spec/unit/swagger/swagger_spec.rb
Currently used swagger parsing library does not support vendor extensions https://github.com/swagger-rb/swagger-rb/issues/5
Issue opened 4 years ago and it does not seem to be fixed soon.
This PR removes `swagger-rb` parser library and implements swagger spec parsing for required elements. Basically, Swagger JSON Schema https://swagger.io/specification/ is used to validate swagger spec and then parsed required elements for 3scale toolbox. Just few lines of code. 
For Openapi 3.0 there is an active repository https://github.com/Nexmo/oas_parser
Fixes #105 
Fixes #93
> Update swagger parser

- docs/openapi.md
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/create_activedocs_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/method.rb
- lib/3scale_toolbox/swagger/swagger.rb
- spec/unit/commands/import_command/openapi/create_activedocs_step_spec.rb
- spec/unit/commands/import_command/openapi/method_spec.rb
- spec/unit/swagger/swagger_spec.rb
The 3scale toolbox detects the provided file does not match the `OpenAPI Specification 2.0 JSON Schema` and prints an error message.
The command is re-run with an additional parameter to skip the OpenAPI Specification validation. When the ActiveDocs is created or updated, the `skip_swagger_validations` field is set to true.
The metric `system_name` field is properly sanitized
Fixes #111
> Import openapi bypass validation

- lib/3scale_toolbox/commands/3scale_command.rb
- lib/3scale_toolbox/commands/copy_command.rb
- lib/3scale_toolbox/commands/import_command.rb
- lib/3scale_toolbox/commands/update_command.rb
> print usage when missing subcommand

- lib/3scale_toolbox.rb
- lib/3scale_toolbox/3scale_client_factory.rb
- lib/3scale_toolbox/base_command.rb
- lib/3scale_toolbox/commands/3scale_command.rb
- lib/3scale_toolbox/proxy_logger.rb
- spec/unit/3scale_client_factory_spec.rb
- spec/unit/proxy_logger_spec.rb
Verbose mode for debugging purposes.
Currently just PoC to be reviewed. Only activated for 3scale API calls, showing parameters sent and returned data, just at library level, not http level.
Method name, arguments and returned result are logged, together with call spent time . Truncated for readability.
Execution example:
```shell
3scale --verbose import openapi -d supertest https://petstore.swagger.io/v2/swagger.json
-- call create_service args |[{"name"=>"Swagger Petstore", "descriptio| response |{"errors"=>{"system_name"=>["has already | - (0.466925691s)
-- call list_services args |[]| response |[{"id"=>2555417723913, "name"=>"Default A| - (0.386342888s)
-- call update_service args |[2555417778023, {"name"=>"Swagger Petstor| response |{"id"=>2555417778023, "name"=>"Swagger Pe| - …
```
> verbose mode on 3scale-api-ruby client calls

- 3scale_toolbox.gemspec
- docs/openapi.md
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/create_service_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/step.rb
- lib/3scale_toolbox/commands/import_command/openapi/threescale_api_spec.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_policies_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_service_oidc_conf_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_service_proxy_step.rb
- lib/3scale_toolbox/swagger/swagger.rb
- spec/integration/import_openapi_spec.rb
- spec/resources/petstore.yaml
- spec/unit/commands/import_command/openapi/create_service_step_spec.rb
- spec/unit/commands/import_command/openapi/threescale_api_spec_spec.rb
- spec/unit/commands/import_command/openapi/update_policies_spec.rb
- spec/unit/commands/import_command/openapi/update_service_oidc_conf_spec.rb
- spec/unit/commands/import_command/openapi/update_service_proxy_spec.rb
- spec/unit/commands/import_command/openapi_spec.rb
- spec/unit/swagger/swagger_spec.rb
Set the correct service authentication settings when importing an OpenAPI Specification based on security requirements.
Fixes #92 
Partially implementing #91, but not fully, just setting `private base URL`
> Openapi import: update service settings based on security reqs

- lib/3scale_toolbox/entities/service.rb
- lib/3scale_toolbox/helper.rb
- lib/3scale_toolbox/tasks/update_service_settings_task.rb
- spec/unit/entities/service_spec.rb
- spec/unit/tasks/update_service_settings_task_spec.rb
When copying a service from 3scale SaaS to an On-premises deployment using the toolbox command and APIcast is configured as self-managed gateway: 
```
3scale copy service 12345678 --source=https://<SaaS_provider_key>@<SaaSdomain>-admin.3scale.net --destination=https://<OnPremprovider_key>@3scale-admin.example.com --target_system_name=abcdefg
```
It outputs the following error: 
```
Error: Service has not been saved. Errors: {"deployment_option"=>["is not included in the list"]}
```
The problem is that 3scale On-premises  doesn't have the self-managed gateway option in the configuration.
> Fix copying self managed service to on prem where invalid

- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/mapping_rule.rb
- lib/3scale_toolbox/commands/import_command/openapi/step.rb
- lib/3scale_toolbox/commands/import_command/openapi/threescale_api_spec.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_policies_step.rb
- spec/custom_matchers.rb
- spec/integration/import_openapi_basepath_spec.rb
- spec/integration/import_openapi_oidc_spec.rb
- spec/integration/import_openapi_spec.rb
- spec/resources/petstore.yaml
- spec/shared_contexts.rb
- spec/unit/commands/import_command/openapi/mapping_rule_spec.rb
- spec/unit/commands/import_command/openapi/threescale_api_spec_spec.rb
- spec/unit/commands/import_command/openapi/update_policies_spec.rb
Implements spec from #91 
Specifically https://github.com/3scale/3scale_toolbox/issues/91#issuecomment-475641632
Adding more integration tests on importing OAS was getting complicated to keep up with single mocked results generic for all test. So I ended up putting each integration test on a different file and share common context. Little refactor was required, but I guess the resulting testing code allows adding more e2e tests about importing OAS.
> Import openapi: update url-rewritting policy

- lib/3scale_toolbox/commands/copy_command/copy_service.rb
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_service_proxy_step.rb
- lib/3scale_toolbox/commands/update_command/update_service.rb
- spec/unit/commands/import_command/openapi/update_service_proxy_spec.rb
**Current situation**
When updating/creating proxy objects (the mapping rules, policies, oidc conf, auth conf, public base URLs), then this requires a second, not very intuitive, API call (i.e. proxy update) to update the proxy object and bump proxy config version.
If the proxy update call is not done, it can be very confusing because the mapping rules will appear in the integration page but they will not appear in the proxy config object. The same applies to mapping rules API calls. They changes will be available on mapping rules endpoints, but not available to the gateway because the proxy proxy config object has not changed.
This behavior is intended. In the API case you need to make several API calls and then bump the version. 
**Proposed changes**
This PR re-orders command tasks to …
> proxy update as last task to update proxy object with latest changes

- lib/3scale_toolbox/commands/remote_command/remote_add.rb
- spec/integration/remote_add_spec.rb
Changed remote validation from list_services to list_accounts
list_services it returns a 403 when calling it from the master user on a master account. Due to this the remote couldn't be added.
> Remote add change validation method

- docs/method.md
- docs/metric.md
- lib/3scale_toolbox/commands/methods_command.rb
- lib/3scale_toolbox/commands/metrics_command.rb
* Fix `metrics` to `metric`
* Fix `methods` to `method`
When command name is `methods`, `3scale method` is also valid. CRI library allows it.
> fix metric method command name

- .dependency_decisions.yml
- .travis.yml
> Fix licenseFinder check

- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/bump_proxy_version_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/create_service_step.rb
- lib/3scale_toolbox/commands/import_command/openapi/step.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_service_proxy_step.rb
- lib/3scale_toolbox/entities/service.rb
- spec/unit/commands/import_command/openapi/bump_proxy_version_step_spec.rb
- spec/unit/commands/import_command/openapi/create_service_step_spec.rb
- spec/unit/commands/import_command/openapi/update_service_proxy_spec.rb
- spec/unit/commands/import_command/openapi_spec.rb
- spec/unit/entities/service_spec.rb
the "3scale import openapi" command has to set the public staging/prod URLs
==================================================================
When importing an OpenAPI, the service is created using the SaaS APIcast but there is no mean to specify a custom public staging/prod URL so that I could use my own APIcast instances.
The "3scale import openapi" command has two more optional parameters :
```
--staging-public-base-url=http://my-apicast-instance.mydomain.com:8080
--production-public-base-url=https://api.example.com
```
> 3scale import openapi set the public staging prod URLs

- lib/3scale_toolbox/commands/plans_command/apply_command.rb
- lib/3scale_toolbox/commands/plans_command/create_command.rb
> change type from int to float of the --cost-per-month and --setup-fee options

- README.md
- docs/copy-policy-registry.md
- lib/3scale_toolbox/commands.rb
- lib/3scale_toolbox/commands/policy_registry_command.rb
- lib/3scale_toolbox/commands/policy_registry_command/copy_command.rb
- spec/unit/commands/policy_registry_command/copy_command_spec.rb
Toolbox command to `copy` policy registry (a.k.a. custom policies) from source tenant to target tenant.
Policy registry identificator is `#{name}-#{version}`. Having this identifying function, we can define
* Missing policies: policies that exist in source tenant and do not exist in target tenant. 
* Matching policies: policies from source tenant that exist in target tenant.
Then:
This behavior makes the command idempotent.
Integration tests not implemented as they require two different provider accounts.
> Copy policy registry

- docs/app-plan.md
- lib/3scale_toolbox/commands/plans_command/apply_command.rb
- lib/3scale_toolbox/commands/plans_command/create_command.rb
- spec/unit/commands/plans_command/apply_command_spec.rb
- spec/unit/commands/plans_command/create_command_spec.rb
On premises does not allow creating application plan with `--end-user-required` set to `true`.
Error raised
```
Error: Application plan has not been created. Errors: {"end_user_required"=>["translation missing: en.activerecord.errors.models.application_plan.attributes.end_user_required.not_allowed"]}
```
Removed optional parameter from command.
> create application plan: remove --end-user-required THREESCALE-2802

- lib/3scale_toolbox/remotes.rb
- spec/unit/remotes_spec.rb
Handle error when local remote does not exist, instead for raising `KeyError` error.
> Fix remote not found

- docs/openapi.md
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/step.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_service_proxy_step.rb
- spec/unit/commands/import_command/openapi/update_service_proxy_spec.rb
Ability to override the private base URL when importing an OpenAPI.
New option parameter for `3scale import openapi` command.
`--override-private-base-url=<value>        Custom private base URL`
By default:  "host" and "schemes" field of the OpenAPI Specification file. 
> openapi: override private base url THREESCALE-2734

- lib/3scale_toolbox/commands/metrics_command/list_command.rb
- lib/3scale_toolbox/commands/plans_command/export/read_plan_methods_step.rb
- lib/3scale_toolbox/commands/plans_command/export/read_plan_metrics_step.rb
- lib/3scale_toolbox/commands/plans_command/export/step.rb
- lib/3scale_toolbox/commands/plans_command/import/import_plan_metrics_step.rb
- lib/3scale_toolbox/commands/plans_command/import/step.rb
- lib/3scale_toolbox/entities/service.rb
- lib/3scale_toolbox/tasks/copy_limits_task.rb
- lib/3scale_toolbox/tasks/copy_mapping_rules_task.rb
- lib/3scale_toolbox/tasks/copy_methods_task.rb
- lib/3scale_toolbox/tasks/copy_metrics_task.rb
- lib/3scale_toolbox/tasks/copy_pricingrules_task.rb
- lib/3scale_toolbox/tasks/copy_task.rb
- spec/integration/commands/plans_command/plan_import_spec.rb
- spec/unit/commands/metrics_command/list_command_spec.rb
- spec/unit/commands/plans_command/import/import_plan_limits_step_spec.rb
- spec/unit/commands/plans_command/import/import_plan_pricing_rules_step_spec.rb
- spec/unit/entities/service_spec.rb
- spec/unit/tasks/copy_limits_task_spec.rb
- spec/unit/tasks/copy_mapping_rules_task_spec.rb
- spec/unit/tasks/copy_pricingrules_task_spec.rb
`GET /admin/api/services/#{service_id}/metrics` returns metrics **AND** methods.
The command output regarding number of metrics was not accurate when copying because methods were included in the total result.
Issues came up in `3scale copy service` command when processing metrics and methods in a separate way (as it should). Scenarios before running copy command that could lead to issues:
* Destination service metric and source service method with same `system_name`
* Destination service method and source service metric with same `system_name`
In those initial scenarios, `3scale copy service` will output warning message and source metric/method will not be copied.
> copy service: fix copy metric task THREESCALE-2613

- lib/3scale_toolbox/commands/proxy_config_command/promote_command.rb
- spec/integration/commands/proxy_config_command/promote_command_spec.rb
- spec/unit/commands/proxy_config_command/promote_command_spec.rb
Related to issue https://github.com/3scale/3scale_toolbox/issues/173.
This PR shows a warning instead of returning an exit code different than 0 when a Staging ProxyConfig environment version has already been promoted to the Production environment.
The behavior now is:
* If ProxyConfig staging for a service does not exist (has never been updated) an error is raised
* If ProxyConfig production for a service does not exist, and promote is executed, the proxyconfiguration is promoted (it means the staging proxyconfiguration had never been promoted)
* If ProxyConfig staging and production for a service are the same a warning is shown and an exit code 0 is returned (normal exit)
* If ProxyConfig staging and production for a service are different the staging configuration is promoted to …
> Make ProxyConfig promote command idempotent

- lib/3scale_toolbox/commands/copy_command/copy_service.rb
- lib/3scale_toolbox/entities/service.rb
- lib/3scale_toolbox/tasks/copy_activedocs_task.rb
- spec/unit/commands/copy_command/service_spec.rb
- spec/unit/entities/service_spec.rb
- spec/unit/tasks/copy_activedocs_spec.rb
Activedocs copy is idempotent. Will update if already exists and create if it does not.
Additionally, added check to `copy service` in case source and target service are the same service
> copy service: copy activedocs idempotent

- spec/helpers.rb
- spec/integration/commands/proxy_config_command/list_command_spec.rb
- spec/integration/commands/proxy_config_command/promote_command_spec.rb
- spec/integration/commands/proxy_config_command/show_command_spec.rb
Integration tests show random failures when proxy config is updated.
This is because proxy config version is not updated synchronously when API is called. If the system is not fast enough creating new proxy version, then trying to promote the new version fails randomly.
Added helper function to retry until timeout is reached. This helper method will make sure 3scale API has time enough to create new proxy config version and be promoted.
> Test wait method to retry until timeout

- docs/applications.md
- lib/3scale_toolbox/commands/application_command/apply_command.rb
- lib/3scale_toolbox/commands/application_command/create_command.rb
- spec/unit/commands/application_command/apply_command_spec.rb
- spec/unit/commands/application_command/create_command_spec.rb
> The 3scale application apply/create is missing an option to set the redirect url THREESCALE-2853

- 3scale_toolbox.gemspec
Bundler uses gem 2.7.6. In this version
```
spec.files         << __FILE__
```
was expanded to the full path, and it could not be installed when gem was published
> fix gemspec file name

- README.md
- lib/3scale_toolbox/commands/update_command.rb
The main help message in toolbox now is shown as:
```
msoriano@localhost:~/repositories/3scale_toolbox (mark-update-service-deprecated)$ bundle exec 3scale --help
NAME
3scale - 3scale toolbox
USAGE
3scale <sub-command> [options]
DESCRIPTION
3scale toolbox to manage your API from the terminal.
COMMANDS
account              account super command
activedocs           activedocs super command
application          application super command
application-plan     application-plan super command
copy                 copy super command
help                 show help
import               import super command
method               method super command
metric               metric super command
policy-registry      policy-registry super command
proxy-config         proxy-config super command
remote …
```
> Mark update supercommand as deprecated in main help message

- docs/applications.md
- lib/3scale_toolbox/commands/application_command/apply_command.rb
- lib/3scale_toolbox/commands/application_command/delete_command.rb
- lib/3scale_toolbox/commands/application_command/show_command.rb
- lib/3scale_toolbox/entities/application.rb
Fix application command documentation to reflect the current criteria order on how an application is found in the toolbox application command
> Fix documentation on evaluation order of application parameter

- examples/Jenkinsfile
One of the main use cases we will promote for the 3scale toolbox is to provision an API from a Jenkins pipeline. 
This is going to be documented in the official Red Hat documentation, in blogs article in the Red Hat Developer Blog, in demos, etc.
To help the community and also to serve as the main source of truth release after release, I'm contributing this sample Pipeline that shows how to use the 3scale toolbox from Jenkins.
> provide a new example: Jenkins pipeline

- Gemfile
- Gemfile.lock
Fixes https://nvd.nist.gov/vuln/detail/CVE-2019-16892
The library affected by the vulnerability issue is a transitive (not direct) dependency on the "development" library `license-finder`. Development library are libraries used in dev-testing and are not included in releases. Hence, it does not affect packaged releases.
> CVE-2019-16892: rubyzip >= 1.3.0 THREESCALE-3731

- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/step.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_service_proxy_step.rb
- spec/integration/commands/import_command/openapi/backend_api_spec.rb
- spec/unit/commands/import_command/openapi/update_service_proxy_spec.rb
Add new options in the import openapi command to allow specifying
a custom host header and a secret token that the API gateway will
send to the configured backend API in the proxy configuration.
> Add custom host header and secret token options for import openapi

- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/mapping_rule.rb
- lib/3scale_toolbox/commands/import_command/openapi/threescale_api_spec.rb
- spec/integration/commands/import_command/openapi/prefix_matching_spec.rb
- spec/unit/commands/import_command/openapi/mapping_rule_spec.rb
- spec/unit/commands/import_command/openapi/threescale_api_spec_spec.rb
Add --prefix-matching in import openapi command.
Pending tests. Tests will be added in this PR once the implemented approach is deemed correct.
> Add prefix matching flag for mapping rules in import openapi command

- docs/activedocs.md
- lib/3scale_toolbox/commands/activedocs_command/apply_command.rb
- spec/integration/commands/activedocs_command/apply_command_spec.rb
- spec/unit/commands/activedocs_command/apply_command_spec.rb
Make activedocs apply command not set skip_swagger_validations on activedocs update.
Notice that this breaks compatibility with possible existing scripts so we should document in the new release that the scripts should be updated. It also changes default behavior, although it is a fix to a behavior that it should not exist.
> Do not set skip_swagger_validation when not provided as an option in activedocs apply

- .circleci/config.yml
- 3scale_toolbox.gemspec
- README.md
ruby 2.4 is almost in EOL date: 2020-03-31
~Support ruby 2.7~
> Deprecate ruby 2.4

- README.md
- docs/errors.md
- lib/3scale_toolbox/cli/error_handler.rb
- lib/3scale_toolbox/error.rb
> Standard way to report errors

- README.md
- docs/proxy-config.md
- lib/3scale_toolbox/commands/proxy_config_command.rb
- lib/3scale_toolbox/commands/proxy_config_command/export_command.rb
- lib/3scale_toolbox/commands/proxy_config_command/helper.rb
- spec/unit/commands/proxy_config_command/export_command_spec.rb
New `proxy-config` subcommand: `export`.
Export proxy configuration to be used as 3scale apicast configuration: https://issues.redhat.com/browse/THREESCALE-669
```
$3scale proxy-config export -h
NAME
export - Export proxy configuration for the entire provider account
USAGE
3scale proxy-config export <remote>
DESCRIPTION
Export proxy configuration for the entire provider account
Can be used as 3scale apicast configuration file
https://github.com/3scale/apicast/blob/master/doc/parameters.md#threescale_config_file
OPTIONS
--environment=<value>      Gateway environment. Must be 'sandbox' or
'production' (default: sandbox)
-o --output=<value>           Output format. One of: json|yaml
```
> Threescale 669: Export apicast configuration file

- .circleci/config.yml
- 3scale_toolbox.gemspec
- Gemfile.lock
- docs/export-import-app-plan.md
- lib/3scale_toolbox/commands/plans_command/import/import_plan_limits_step.rb
- lib/3scale_toolbox/commands/plans_command/import/import_plan_pricing_rules_step.rb
- lib/3scale_toolbox/entities/application_plan.rb
- spec/unit/commands/plans_command/import/import_plan_limits_step_spec.rb
- spec/unit/commands/plans_command/import/import_plan_pricing_rules_step_spec.rb
Application plan import command takes as source of truth the imported resource
> Application plan import: input resource as source of truth

- docs/copy-product.md
- docs/copy-service.md
- lib/3scale_toolbox/commands/service_command/copy_command/copy_service_proxy_task.rb
- spec/unit/commands/service_command/copy_command/copy_service_proxy_task_spec.rb
Service copy command: do not copy endpoint url for services with hosted gateway
> service copy command fix: do not copy endpoint url hosted services

- spec/integration/commands/proxy_config_command/list_command_spec.rb
- spec/integration/commands/proxy_config_command/promote_command_spec.rb
- spec/integration/commands/proxy_config_command/show_command_spec.rb
- spec/shared_contexts.rb
Service needs backend api. Otherwise proxy config will not be promoted to sandbox. This behavior was changed when APIaP was implemented.
> fix proxy config integration tests

- lib/3scale_toolbox/openapi/oas3.rb
- spec/shared_oas3_contexts.rb
- spec/unit/openapi/oas3_spec.rb
When importing an OAS 3.0.2 spec, the 3scale toolbox converts custom ports to the default protocol (e.g. 80/HTTP) in the Backend definition
https://issues.redhat.com/browse/THREESCALE-6192
> oas3: fix custom ports for backend url

- README.md
- docs/export-import-policy-chain.md
- lib/3scale_toolbox/commands.rb
- lib/3scale_toolbox/commands/policies_command.rb
- lib/3scale_toolbox/commands/policies_command/export_command.rb
- lib/3scale_toolbox/commands/policies_command/import_command.rb
- spec/unit/commands/policies_command/export_command_spec.rb
- spec/unit/commands/policies_command/import_command_spec.rb
* `3scale policies export` command to export one product's policy chain to yaml/json format
* `3scale policies import` command to import one product's policy chain from yaml/json format
> policies command, import and export

- Dockerfile
Currently, `centos/ruby-25-centos7:latest` base image with tag `centos/ruby-25-centos7@sha256:71a4818652959d2c03e98b42ad74571426fb5ccab3f93448ba1dd2524a6ad0ef`  breaks the build:
```
$ docker run --rm -ti quay.io/redhat/3scale-toolbox:master 3scale help
/usr/bin/container-entrypoint: line 2: exec: 3scale: not found
```
> Change base image: ruby:2.7

- .circleci/config.yml
Nightly smoke test of the docker docker image.
Main value: monitor the base image changes that could potentially break the build
> ci job to check docker image

- docs/openapi.md
- lib/3scale_toolbox/commands/import_command/issuer_type_transformer.rb
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/import_command/openapi/step.rb
- lib/3scale_toolbox/commands/import_command/openapi/update_service_proxy_step.rb
- spec/unit/commands/import_command/openapi/update_service_proxy_spec.rb
Added optional parameter to openapi import spec to allow setting oidc issuer type.
Updated documentation to reflect new argument in openapi import command.
Added unit tests to verify new argument is working correctly and is compatible with earlier versions.
There are no license changes in this commit.
> Added optional argument to openapi import command to allow setting oidc issuer type

- README.md
- docs/proxy-config.md
- lib/3scale_toolbox/commands/proxy_config_command.rb
- lib/3scale_toolbox/commands/proxy_config_command/deploy_command.rb
- lib/3scale_toolbox/entities/service.rb
- spec/unit/commands/proxy_config_command/deploy_command_spec.rb
- spec/unit/entities/service_spec.rb
Command to promote the APIcast configuration to the Staging Environment 
Only supported in 3scale release >= 2.7
Requires: https://github.com/3scale/3scale-api-ruby/pull/94
Jira Issue: https://issues.redhat.com/browse/THREESCALE-6620
> new command: 3scale proxy-config deploy

- lib/3scale_toolbox/commands/import_command/openapi/create_method_step.rb
- spec/unit/commands/import_command/openapi/create_methods_step_spec.rb
When the command `import openapi` was called twice with the same OpenAPI file spec toolbox returned a `NoMethodError` error, with the import execution failing.
The returned data types were incorrect and used methods could not be
found. This fixes it.
Related to issue https://github.com/3scale/3scale_toolbox/issues/291
> import/openapi/create_method_step: fix nomethoderror when importing twice

- .circleci/config.yml
CircleCI does not run workflows for tags unless you explicitly specify tag filters.
> enable unittest for tag builds

- .circleci/config.yml
- .travis.yml
- .travis/build_ppc64le.sh
- .travis/install_ppc64le_env.sh
- .travis/setup_ppc64le_env.sh
- Gemfile.lock
Fix for CVE-2020-36327 rubygem-bundler: Dependencies of gems with explicit source may be installed from a different source
https://issues.redhat.com/browse/THREESCALE-7085
> bundler using v2.2.21

- Dockerfile
`registry.access.redhat.com` is deprecated and new images are not shipped, exept for a select group, namely the ubi images. 
It is unauthenticated and easier to manage internal builds.
> update base image to  publicly available unauthenticated registry

- docs/copy-backend.md
- docs/copy-product.md
- lib/3scale_toolbox/commands/backend_command/copy_command.rb
- lib/3scale_toolbox/commands/backend_command/copy_command/delete_mapping_rules_task.rb
- lib/3scale_toolbox/commands/backend_command/copy_command/task.rb
- lib/3scale_toolbox/commands/product_command/copy_command.rb
- lib/3scale_toolbox/commands/product_command/copy_command/copy_backends_task.rb
- lib/3scale_toolbox/commands/product_command/import_command.rb
- spec/unit/commands/backend_command/copy_command/delete_mapping_rules_task_spec.rb
- spec/unit/commands/backend_command/copy_command_spec.rb
https://issues.redhat.com/browse/THREESCALE-7215
Fixes #306
> [breaking change] mapping rules will be replaced instead of adding missing rules

- Gemfile.lock
Add powerpc64le-linux platform
The outcome of executing
```
bundle lock --add-platform powerpc64le-linux
```
Bundler is smart enough to use platform dependent gems whenever available in the lock file. This is desired as nokogiri [recommends](https://github.com/sparklemotion/nokogiri#native-gems-faster-more-reliable-installation) using native gems with precompiled binaries
> Gemfile.lock: add powerpc64le-linux platform

- lib/3scale_toolbox/commands/import_command/openapi.rb
- spec/unit/commands/import_command/openapi_spec.rb
The '`3scale import openapi` command did not check parsed format when `YAML.safe_load` returned a `string` (which is a valid yaml doc, but not for OAS docs)
```bash
3scale import openapi -d supertest - <<EOF
>  <!DOCTYPE html>
> <html>
> <body>
> 
> <h1>My First Heading</h1>
> <p>My first paragraph.</p>
> 
> </body>
> </html> 
> EOF
{
"code": "E_UNKNOWN",
"message": "undefined method `key?' for #<String:0x000055bb120097b8>",
"class": "NoMethodError",
"stacktrace": [
"/home/eguzki/git/3scale_toolbox/lib/3scale_toolbox/commands/import_command/openapi.rb:111:in `openapi_parser'",
"/home/eguzki/git/3scale_toolbox/lib/3scale_toolbox/commands/import_command/openapi.rb:78:in `create_context'",
"/home/eguzki/git/3scale_toolbox/lib/3scale_toolbox/commands/import_command/openapi.rb:72:in …
```
> detect OAS format error

- 3scale_toolbox.gemspec
- Gemfile.lock
- README.md
- docs/activedocs.md
- docs/app-plan.md
- docs/applications.md
- docs/copy-policy-registry.md
- docs/export-import-app-plan.md
- docs/method.md
- docs/metric.md
- docs/proxy-config.md
- docs/service.md
- lib/3scale_toolbox/3scale_client_factory.rb
- lib/3scale_toolbox/base_command.rb
- lib/3scale_toolbox/commands/3scale_command.rb
- spec/unit/3scale_client_factory_spec.rb
Currently, each 3scale admin API call required to setup a new TCP/HTTP connection. For 3scale commands running multiple 3scale API calls, the toolbox spends a lot of time on TCP/HTTP connection setup. Specially true for TLS connections.
With this change, by default, the connection opened by the 3scale toolbox command (if the command requires opening a connection) will be setup to keep alive. Thus, all API calls required for the command will reuse the connection.
If, for whatever reason, the `Connection: close` behavior is desired, the PR includes a new top level option parameter:
```
--disable-keep-alive       Disable keep alive HTTP connection mode
```
> Setup keep alive connections

- lib/3scale_toolbox/resource_reader.rb
- spec/unit/resource_reader_spec.rb
Minor improvement to support passing `stringio` for convenience,  
This is mainly because I have a use case to read resources in a plugin, before invocation of `ResourceReader` module and no need to do the read operation twice.
Specs added and passing:
```bash
$ rspec spec/unit/resource_reader_spec.rb
Randomized with seed 29683
ThreeScaleToolbox::ResourceReader
#load_resource
invalid json
raises error
valid json
does not return nil
is loaded
valid yaml
does not return nil
is loaded
invalid yaml
raises error
#read_content
from URL
behaves like content is read
does not return nil
is read
from stdin
behaves like content is read
is read
does not return nil
from stringio
behaves like content is read
does not return nil
is read
from folder
error is raised
from file
behaves like content is read …
```
> Support StringIO object as format of ResourceReader

- .circleci/config.yml
CircleCI `docker:stable` image does not have `bin/bash`
> Fix CI docker image test

- lib/3scale_toolbox/commands/activedocs_command/apply_command.rb
- lib/3scale_toolbox/commands/activedocs_command/create_command.rb
- lib/3scale_toolbox/commands/import_command/openapi.rb
- lib/3scale_toolbox/commands/plans_command/import_command.rb
- lib/3scale_toolbox/commands/policies_command/import_command.rb
- lib/3scale_toolbox/commands/product_command/import_command.rb
- lib/3scale_toolbox/resource_reader.rb
- spec/unit/resource_reader_spec.rb
The flag to skip TLS verification was available for HTTP connections against 3scale API. This PR adds the option to skip TLS verification for HTTP connections used to read external resources. Used for commands like`3scale import openapi` where the OAS doc is hosted in some URL.
https://issues.redhat.com/browse/THREESCALE-7850
> verify_ssl option on resource_reader by URL

- Gemfile.lock
commands run to update
```
bundle lock --add-platform ruby
bundle lock --remove-platform powerpc64le-linux
bundle lock --remove-platform s390x-linux
bundle lock --remove-platform x86_64-linux
```
> ruby as the only platform

- CHANGELOG.md
- lib/3scale_toolbox/commands/application_command/apply_command.rb
- spec/unit/commands/application_command/apply_command_spec.rb
Jira: https://issues.redhat.com/browse/THREESCALE-8707
The source issue was that applications were created populating both `user_key` and `application_id` regardless of the product's authentication mode (`backend_version` attr). When the auth mode is `user_key` (`backend_version` attr equals `'1'`), the `application_id` was also populated. After user key regeneration, the user_key changed but not the `application_id`. When the toolbox asked for an application with user_key `application_parameter10`,3scale returned not found as expected. Then the toolbox asked for an application with application _id `application_parameter10` which existed, but since the auth mode is `user_key` 3scale still returned not found. In the last step, when the toolbox tried to create a new app with application_id …
> THREESCALE-8707 Fix apply app

- docs/openapi.md
- lib/3scale_toolbox/commands/import_command/openapi/update_service_oidc_conf_step.rb
- lib/3scale_toolbox/openapi/oas3.rb
- lib/3scale_toolbox/openapi/swagger.rb
- spec/shared_oas3_contexts.rb
- spec/unit/commands/import_command/openapi/update_service_oidc_conf_spec.rb
- spec/unit/openapi/oas3_spec.rb
- spec/unit/openapi/swagger_spec.rb
Fixes https://issues.redhat.com/browse/THREESCALE-9768
> THREESCALE-9768 OpenAPI support for multiple flows in oauth
